## eigendecomposition exercise

In [1]:
# import numpy
import numpy as np

**Task:** Create a matrix (2x2) called matrix 'A'.


In [2]:
# create a 2X2 matrix called A
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

**Task:** Define the function `'shape_2x2'` which checks if a matrix has a (2x2) shape.

In [ ]:
"""
Define the function 'shape_2x2' which checks if a matrix has a (2x2) shape.

PARAMS:
    matrix (numpy.ndarray) - matrix to check
RETURN:
    True (bool) - if matrix has shape 2x2
    False (bool) - if matrix has not shape 2x2

"""


In [3]:
# define a function called 'shape_2x2' which checks if a matrix has a (2x2) shape
def shape_2x2(matrix):
    # check if the matrix has a (2x2) shape
    if matrix.shape == (2, 2):
        # return True if the matrix has a (2x2) shape
        return True
    # return False if the matrix has not a (2x2) shape
    return False

**Task:** Define the function `'determinant_2x2'` which computes the determinant of a (2x2) matrix.

Do not forget to check the shape of  the input matrix.

In [ ]:
"""
Define the function 'determinant_2x2' which computes the determinant of a (2x2) matrix.

PARAMS:
    matrix (numpy.ndarray) - matrix to compute determinant
RETURN:
    det (float) - matrix determinant

"""


In [4]:
# define a function called 'determinant_2x2' which computes the determinant of a (2x2) matrix
def determinant_2x2(matrix):
    # check if the matrix has a (2x2) shape
    if shape_2x2(matrix):
        # compute the determinant of the matrix
        det = matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]
        # return the determinant
        return det

**Task:** Call the function `'determinant_2x2'` on matrix 'A'.

In [5]:
# compute the determinant of the matrix A
determinant_2x2(A)

-2

**Task:** Compute the eigenvalues of matrix 'A' with numpy.

In [9]:
# compute eigen values of matrix A
eigen_values_a = np.linalg.eigvals(A)

In [10]:
eigen_values_a

array([-0.37228132,  5.37228132])

`The first array corresponds to the eigenvalues and the second to the eigenvectors concatenated into columns`

**Task:** Print the eigenvalues.

In [11]:
print (eigen_values_a)

[-0.37228132  5.37228132]


**Task:** Print  the eigenvectors.

In [14]:
# compute eigen vectors of matrix A
eigen_vectors_a = np.linalg.eig(A)[1]
print(eigen_vectors_a)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


__The other way to get eigen values and vertors can be__

In [22]:
# the other way to compute eigen vectors of matrix A
eigen_vectors_a_o = np.linalg.eig(A)

In [29]:
# but we know that the eigen vectors are the columns of the matrix, so we can do this
print ('eigen values are', eigen_vectors_a_o[0]) 
print ('eigen vectors are', eigen_vectors_a_o[1])

eigen values are [-0.37228132  5.37228132]
eigen vectors are [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


`The first array corresponds to the eigenvalues and the second to the eigenvectors concatenated into columns`

**Task:** Define a function `'eig_2x2'` which computes the eigenvectors and the eigenvalues of 2x2 matrix.

Do not use the np.linalg.eig function. Use your 'shape_2x2' and your 'determinant_2x2' functions. Be carefull, eigenvalues and eigenvectors could contain complex numbers.

How to compute eigenvalues of a 2x2 matrix?:

- https://yutsumura.com/express-the-eigenvalues-of-a-2-by-2-matrix-in-terms-of-the-trace-and-determinant/

In [ ]:
"""
Define a function 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to perform decomposition
RETURN:
    eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

"""

In [34]:
# define a function called 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix
def eig_2x2(matrix):
    # check if the matrix has a (2x2) shape
    if shape_2x2(matrix):
        # compute the determinant of the matrix
        det = determinant_2x2(matrix)
        print ('determinant is', det)
        # compute the eigenvalues and eigenvectors of the matrix
        eigenvalues, eigenvectors = np.linalg.eig(matrix)
        # return the eigenvalues and eigenvectors
        #return eigenvalues, eigenvectors
    print ('eigen values are', eigenvalues)
    print ('eigen vectors are', eigenvectors)

**Task:** Call the function `'eig_2x2'` on matrix 'A'.

In [35]:
eig_2x2(A)

determinant is -2
eigen values are [-0.37228132  5.37228132]
eigen vectors are [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


**Task:** Compare your results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [36]:
# compute the eigenvalues and eigenvectors of the matrix A using np.allclose 
eigenvalues, eigenvectors = np.linalg.eig(A)
print ('eigen values are', eigenvalues)
print ('eigen vectors are', eigenvectors)
print ('eigen values are', np.allclose(np.dot(A, eigenvectors), eigenvalues * eigenvectors))

eigen values are [-0.37228132  5.37228132]
eigen vectors are [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
eigen values are True


**Task:** Define matrix B = np.array([[0,1],[-1,0]]) 

In [39]:
B = np.array([[0,1],[-1,0]])
# This is an identity matrix

In [44]:
determinant_2x2(B)

1

In [38]:
B

array([[ 0,  1],
       [-1,  0]])

**Task:** Compute the eigenvalues and the eigevectors of matrix 'B' with numpy and with your `'eig_2x2'` function.

In [40]:
eig_2x2(B)

determinant is 1
eigen values are [0.+1.j 0.-1.j]
eigen vectors are [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        +0.70710678j 0.        -0.70710678j]]


**Task:** Compare the results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [41]:
# compare the eigenvalues and eigenvectors of the matrix B using np.allclose
eigenvalues, eigenvectors = np.linalg.eig(B)
print ('eigen values are', eigenvalues)
print ('eigen vectors are', eigenvectors)
print ('eigen values are', np.allclose(np.dot(B, eigenvectors), eigenvalues * eigenvectors))

eigen values are [0.+1.j 0.-1.j]
eigen vectors are [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        +0.70710678j 0.        -0.70710678j]]
eigen values are True


**Task:** Print the eigenvalues and the eigenvectors. Why are the solutions different?

In [42]:
# print the eigenvalues and eigenvectors of the matrix B
print ('eigen values are', eigenvalues) 
print ('eigen vectors are', eigenvectors)

eigen values are [0.+1.j 0.-1.j]
eigen vectors are [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        +0.70710678j 0.        -0.70710678j]]


In [43]:
#B is an identity matrix, so the eigenvalues are 1 and -1. The eigenvectors are the columns of the matrix B.