## Matrix Decomposition Exercise

In [2]:
# import numpy
import numpy as np
import numpy.linalg as la

**Task:** Generate a random matrix 'A' with a shape of 150x50, using the '**np.random.rand**' function.

In [3]:
# generate a random matrix A with shape 150X50 using np.random.rand
A = np.random.rand(150, 50)

**Task:** Check the shape of 'A'.

In [4]:
type(A)

numpy.ndarray

**Task:** Decompose matrix 'A' with SVD using numpy (decompose into matrices U,D,V).

In [6]:
# compute the SVD decomposition of A into U, D, V
U, D, V = la.svd(A)

array([[-0.09204877,  0.01279412,  0.03473779, ...,  0.01715618,
        -0.03796863,  0.0509997 ],
       [-0.08855303, -0.12115667, -0.10946121, ...,  0.20903596,
         0.026753  ,  0.11821637],
       [-0.07131422,  0.0207151 ,  0.03116559, ...,  0.09438811,
        -0.00873368, -0.08155166],
       ...,
       [-0.07542946,  0.05659156, -0.01532432, ...,  0.71371203,
         0.00775152, -0.01544007],
       [-0.08816231, -0.13831353, -0.01821508, ..., -0.04840357,
         0.67673543,  0.00551594],
       [-0.08529183, -0.07956693, -0.07580399, ..., -0.04636658,
        -0.0455376 ,  0.69703257]])

**Task:** Check the shapes of matrices U,D,V.

In [8]:
# check the shape of U, D, V
U.shape, D.shape, V.shape

((150, 150), (50,), (50, 50))

**Task:** Reconstruct matrix 'A' from matrices U,D,V.

In [29]:
#Reconstruct matrix A from matrix U,D,V
def reconstruct_matrix(U,D,V):
    A = np.zeros((U.shape[0],V.shape[0]))
    for i in range(U.shape[0]):
        for j in range(V.shape[0]):
            A[i,j] = np.dot(U[i,:],D[j,:]) + V[j,:]

    return


In [30]:
reconstruct_matrix(U,D,V)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Task:** Compare matrices 'A' and 'A_rec' with the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function.

In [22]:
# compare the reconstructed matrix A with the original matrix A
np.allclose(A, A_reconstructed)

NameError: name 'A_reconstructed' is not defined

**Task:** Reduce the dimnesion of matrix 'A' to shape 150x20 with SVD (try both equations).

**Task:** Print the shape.

**Task:** Compare the two results with the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function.

**Task:** Filter the noise from matrix 'A' with 20 largest singular vectors (keep the shape of (150x50)).

**Task:** Check the shape.

**Task:** Define the function `'SVD'` which perform singular values decomposition.

Do not forget to hceck the shape of the input matrix.

In [ ]:
"""
PARAMS:
    A (numpy.ndarray) - matrix to decompose
RETURN:
    U (numpy.ndarray) - left singular vectors
    SV (numpy.ndarray) - singular values
    V (numpy.ndarray) - right singular vectors
"""

In [31]:
# define a function to compute the SVD decomposition of a matrix A, check shape of A
def svd_decomposition(A):
    # compute the eigenvalues and eigenvectors of A.T.dot(A)
    eigenvalues, eigenvectors = la.eig(A.T.dot(A))
    # compute the singular values of A
    SV = np.sqrt(eigenvalues)
    # compute the right singular vectors of A
    V = eigenvectors
    # compute the left singular vectors of A
    U = A.dot(V) / SV

    return U, SV, V


**Task:** Call the function `'SVD'` on matrix 'A'.

In [35]:
svd_decomposition(A)

(array([[ 0.09204877,  0.01279412, -0.03473779, ...,  0.02891002,
          0.06522504,  0.11899686],
        [ 0.08855303, -0.12115667,  0.10946121, ..., -0.11413244,
         -0.04629654, -0.04294377],
        [ 0.07131422,  0.0207151 , -0.03116559, ..., -0.13700367,
          0.03761662,  0.08489287],
        ...,
        [ 0.07542946,  0.05659156,  0.01532432, ..., -0.03608659,
          0.03077485,  0.03393097],
        [ 0.08816231, -0.13831353,  0.01821508, ..., -0.18486012,
         -0.0904936 ,  0.05698812],
        [ 0.08529183, -0.07956693,  0.07580399, ..., -0.15939124,
         -0.05353889,  0.03980514]]),
 array([43.49040837,  5.3784808 ,  5.29412351,  5.20976611,  4.99127357,
         4.8643742 ,  4.8208973 ,  4.65575826,  4.64056591,  4.52754419,
         4.48228417,  4.42140093,  4.32786129,  4.26049862,  4.08854326,
         4.07355638,  3.98923881,  3.89826458,  1.51457713,  3.77228302,
         1.72000016,  3.69273999,  3.61305437,  3.58527306,  3.53599862,
        

In [37]:
# check the shape of U, SV, V
