## Matrix Decomposition Exercise

In [1]:
# import numpy
import numpy as np
import numpy.linalg as la

**Task:** Generate a random matrix 'A' with a shape of 150x50, using the '**np.random.rand**' function.

In [2]:
# generate a random matrix A with shape 150X50 using np.random.rand
A = np.random.rand(150, 50)

In [4]:
A.shape

(150, 50)

**Task:** Check the shape of 'A'.

In [4]:
type(A)

numpy.ndarray

In [52]:
A

array([[0.66128793, 0.29915272, 0.4189794 , ..., 0.96400086, 0.89466405,
        0.32548925],
       [0.82780919, 0.95600038, 0.66456902, ..., 0.21419636, 0.15869064,
        0.11871241],
       [0.0522388 , 0.58790744, 0.6148755 , ..., 0.14994106, 0.98970858,
        0.10840065],
       ...,
       [0.54210867, 0.69398983, 0.03238269, ..., 0.28854778, 0.30393316,
        0.9706647 ],
       [0.23780887, 0.0184847 , 0.25413318, ..., 0.90945687, 0.30314467,
        0.50906294],
       [0.21462548, 0.00674328, 0.54279745, ..., 0.036953  , 0.66425386,
        0.20038745]])

**Task:** Decompose matrix 'A' with SVD using numpy (decompose into matrices U,D,V).

In [40]:
#decompose A into U, D, V using np.linalg.svd
U, D, V = la.svd(A, full_matrices=True)

**Task:** Check the shapes of matrices U,D,V.

In [39]:
# check the shape of U, D, V
U.shape, D.shape, V.shape

((150, 50), (50,), (50, 50))

In [43]:
# check if U is singular vector
U.dot(U.T)


array([[ 1.00000000e+00, -4.91070060e-17, -2.00291204e-17, ...,
         1.43328465e-16,  9.60333532e-17, -4.94922873e-17],
       [-4.91070060e-17,  1.00000000e+00,  1.06290233e-17, ...,
         9.73555550e-17, -1.53647579e-16, -2.03791396e-17],
       [-2.00291204e-17,  1.06290233e-17,  1.00000000e+00, ...,
        -2.21715721e-16, -5.41166350e-17,  9.23292199e-17],
       ...,
       [ 1.43328465e-16,  9.73555550e-17, -2.21715721e-16, ...,
         1.00000000e+00,  6.56502195e-17, -7.09293821e-17],
       [ 9.60333532e-17, -1.53647579e-16, -5.41166350e-17, ...,
         6.56502195e-17,  1.00000000e+00, -4.18089095e-17],
       [-4.94922873e-17, -2.03791396e-17,  9.23292199e-17, ...,
        -7.09293821e-17, -4.18089095e-17,  1.00000000e+00]])

In [44]:
# check if D is singular value
D

array([43.0074422 ,  5.27802896,  5.20183577,  5.16238124,  5.01234252,
        4.82023172,  4.76017469,  4.64206788,  4.54458904,  4.47977546,
        4.33742272,  4.29330008,  4.27106758,  4.22955321,  4.08359278,
        4.00933756,  3.95908924,  3.94085444,  3.81270545,  3.74406647,
        3.70863564,  3.61552426,  3.49829011,  3.43357742,  3.40813967,
        3.35604969,  3.26749325,  3.22410649,  3.1438986 ,  3.11800214,
        3.06380287,  3.00716935,  2.91057466,  2.79866153,  2.77038005,
        2.7192177 ,  2.62524492,  2.54860197,  2.5124871 ,  2.41970012,
        2.4000906 ,  2.34505787,  2.17760427,  2.11048846,  2.06833975,
        2.02735425,  1.94936414,  1.85467292,  1.73167601,  1.53133801])

In [45]:
# check if V is right singular vector
V.dot(V.T)

array([[ 1.00000000e+00, -1.34255083e-17, -6.55261124e-17, ...,
        -3.57673268e-17, -5.32846731e-17,  3.22486001e-17],
       [-1.34255083e-17,  1.00000000e+00, -2.44284834e-16, ...,
        -4.26214821e-17,  9.74687791e-17, -4.51496779e-17],
       [-6.55261124e-17, -2.44284834e-16,  1.00000000e+00, ...,
         6.15293735e-18, -1.78803635e-17,  2.91655998e-16],
       ...,
       [-3.57673268e-17, -4.26214821e-17,  6.15293735e-18, ...,
         1.00000000e+00,  3.48885748e-16,  8.45525392e-17],
       [-5.32846731e-17,  9.74687791e-17, -1.78803635e-17, ...,
         3.48885748e-16,  1.00000000e+00, -7.12364296e-17],
       [ 3.22486001e-17, -4.51496779e-17,  2.91655998e-16, ...,
         8.45525392e-17, -7.12364296e-17,  1.00000000e+00]])

**Task:** Reconstruct matrix 'A' from matrices U,D,V.

In [46]:
# crete a diagonal matrix D_ with the same shape as A
D_ = np.zeros_like(A)

In [48]:
# fill D_ with D
D_[:D.shape[0], :D.shape[0]] = np.diag(D)


In [49]:
from numpy.linalg import multi_dot

In [50]:
# use multi_dot to reconstruct A
A_ = multi_dot([U, D_, V])


In [51]:
A_

array([[0.66128793, 0.29915272, 0.4189794 , ..., 0.96400086, 0.89466405,
        0.32548925],
       [0.82780919, 0.95600038, 0.66456902, ..., 0.21419636, 0.15869064,
        0.11871241],
       [0.0522388 , 0.58790744, 0.6148755 , ..., 0.14994106, 0.98970858,
        0.10840065],
       ...,
       [0.54210867, 0.69398983, 0.03238269, ..., 0.28854778, 0.30393316,
        0.9706647 ],
       [0.23780887, 0.0184847 , 0.25413318, ..., 0.90945687, 0.30314467,
        0.50906294],
       [0.21462548, 0.00674328, 0.54279745, ..., 0.036953  , 0.66425386,
        0.20038745]])

**Task:** Compare matrices 'A' and 'A_rec' with the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function.

In [53]:
# compare the reconstructed matrix A with the original matrix A
np.allclose(A, A_)

True

**Task:** Reduce the dimnesion of matrix 'A' to shape 150x20 with SVD (try both equations).

In [91]:
#1 
A_reduced1 = U[:, :20] * D[:20]
#2 
A_reduced2 = A.dot(V[:20,:].T)

**Task:** Print the shape.

In [89]:
A_reduced1.shape, A_reduced2.shape

((150, 20), (150, 20))

**Task:** Compare the two results with the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function.

In [90]:
# compare the shape of A1, A2, A3 using np.allclose
np.allclose(A_reduced1, A_reduced2)

True

**Task:** Filter the noise from matrix 'A' with 20 largest singular vectors (keep the shape of (150x50)).

In [94]:
# filter noise from A with 20 largest singular vectors
A_reduced = A.dot(V[:20,:].T)

**Task:** Check the shape.

In [95]:
A_reduced.shape

(150, 20)

**Task:** Define the function `'SVD'` which perform singular values decomposition.

Do not forget to hceck the shape of the input matrix.

In [ ]:
"""
PARAMS:
    A (numpy.ndarray) - matrix to decompose
RETURN:
    U (numpy.ndarray) - left singular vectors
    SV (numpy.ndarray) - singular values
    V (numpy.ndarray) - right singular vectors
"""

In [110]:
# define a function to compute the SVD decomposition of a matrix A, check shape of A
def svd_decomposition(A):
    # compute the eigenvalues and eigenvectors of A.T.dot(A)
    eigenvalues, eigenvectors = la.eig(A.T.dot(A))
    # compute the singular values of A
    S = np.sqrt(eigenvalues)
    SV = np.sqrt(eigenvalues)
    # compute the right singular vectors of A
    V = eigenvectors
    # compute the left singular vectors of A
    U = A.dot(V) / SV
    return U, SV, V


**Task:** Call the function `'SVD'` on matrix 'A'.

In [112]:
svd_decomposition(A)

(array([[-8.16569139e-02+0.00000000e+00j, -1.19041748e-01+0.00000000e+00j,
          4.69822013e-02+0.00000000e+00j, ...,
         -3.70886991e-09-2.45244439e-09j, -3.73565543e-09+2.73971862e-09j,
          0.00000000e+00+1.70126329e-09j],
        [-9.10000138e-02+0.00000000e+00j, -5.06013974e-02+0.00000000e+00j,
         -9.30484255e-03+0.00000000e+00j, ...,
          3.04844110e-10+4.61303003e-09j,  5.28440982e-10-4.33361627e-09j,
          0.00000000e+00-6.56424446e-09j],
        [-8.86241195e-02+0.00000000e+00j, -8.62552230e-02+0.00000000e+00j,
         -1.24717193e-01+0.00000000e+00j, ...,
         -4.55159111e-09+9.08413928e-09j, -4.46216883e-09-9.08694659e-09j,
          0.00000000e+00-4.50457910e-09j],
        ...,
        [-8.78430046e-02+0.00000000e+00j,  9.14618924e-02+0.00000000e+00j,
          1.94232583e-03+0.00000000e+00j, ...,
         -2.72386793e-09-2.93173611e-09j, -2.30362436e-09+2.63210971e-09j,
          0.00000000e+00+1.33149632e-08j],
        [-8.33704245e-02+0.

In [113]:
# check the shape of U, SV, V
U.shape



(150, 50)

In [114]:
V.shape

(50, 50)

In [115]:
SV

NameError: name 'SV' is not defined

In [109]:
single_values

NameError: name 'single_values' is not defined